{% set name = "xray-vision" %}
{% set version = "0.0.10" %}
{% set sha256 = "35446f098dfdaadfc25f29f8df16d3dac5c46adc4741fadfd012a9ade3e96efe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Nikea/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib
    - numpy
    - pyqt
    - six

test:
  imports:
    - PyQt5
    - xray_vision
    - xray_vision.backend
    - xray_vision.backend.mpl
    - xray_vision.mask
    - xray_vision.messenger
    - xray_vision.messenger.mpl
    - xray_vision.mpl_plotting
    - xray_vision.qt_widgets
    - xray_vision.utils

about:
  home: https://github.com/Nikea/xray-vision
  license: 3-Clause BSD
  license_file: LICENSE
  summary: Visualization widgets and plotting helpers targeted at X-Ray Sciences
